### ISSUE TITLE
Galaxies attribute in introduction.ipynb on Binder

### ISSUE THREAD

**Issue by alexandergagliano** [Jammy2211/PyAutoGalaxy#32]
When uncommenting the line `result = search.fit(model=model, analysis=analysis)` in the main `introduction.ipynb` notebook, I get the error: AttributeError: 'ModelInstance' object has no attribute 'galaxies'. Connected to [#4475](https://github.com/openjournals/joss-reviews/issues/4475).

**Comment by Jammy2211** [comment]
Good spot, this is fixed by changing:

`model = af.Collection(galaxy=galaxy_model)`

to:

`model = af.Collection(galaxies=af.Collection(galaxy=galaxy_model))`

I have updated the notebook locally and will push the fix once my full suite of integration tests have run.

**Comment by Jammy2211** [comment]
Also going to figure out why the animations / visuals are not displaying on the noteobook :/
