### ISSUE TITLE
Unexpected keywords

### ISSUE THREAD

**Issue by sloneil** [Jammy2211/PyAutoGalaxy#38]
In the notebooks InversionPlotter and VoronoiDrawer, the examples calling 'plane.to_inversion.inversion_imaging_from(...)' is passed 'grid=imaging.grid', but this gives the error
inversion_imaging_from() got an unexpected keyword argument 'grid'

I also get the error
init() got an unexpected keyword argument 'origin'
when calling
yx_plotter.figure_1d()
in the FillBetween notebook

Should these be a different keywords?

**Comment by sloneil** [comment]
I also get the error
__init__() got an unexpected keyword argument 'origin'
when calling 
yx_plotter.figure_1d()
in the FillBetween notebook

**Comment by sloneil** [comment]
The line
result = search.fit(model=model, analysis=analysis)
in the light_pixelized notebooks gives:
'Interferometer' object has no attribute 'grid_inversion'

**Comment by Jammy2211** [comment]
Are you on the `master` branch of the PyAutoArray / PyAutoGalaxy github repos (via a git clone)?

**Comment by sloneil** [comment]
I believe I am.  I've tried recloning it but still get the same error.

**Comment by Jammy2211** [comment]
The updated workspace should fix this, provided you are using the latest `master` branch of other projects.

A pip release is coming soon, once final tests are complete.
