### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by sloneil** [Jammy2211/PyAutoGalaxy#39]
In the GetDist notebook, I was not able to import 'getdist'
in UltraNestPlotter, I was missing 'ultranest'
and in light_centre and mask, I was missing 'autolens'

Did I miss part of the installation?

**Comment by Jammy2211** [comment]
The autolens imports were a mistake which is now fixed.

getidst / ultranest are optional libraries and therefore not installed by default. I have added the following note to the tutorials:

```
Installation
------------

Because UltraNest is an optional library, you will likely have to install it manually via the command:

`pip install ultranest`
```

```
Installation
------------

Because GetDist is an optional library, you will likely have to install it manually via the command:

`pip install getdist`
```
