### ISSUE TITLE
fit model trying to get shapes of ints

### ISSUE THREAD

**Issue by sloneil** [Jammy2211/PyAutoGalaxy#40]
In the tutorial_3_x2_galaxies and parametric_to_pixelized,
result_1 = search_1.fit(model=model_1, analysis=analysis_1)
gave 'int' object has no attribute 'shape'
and I couldn't find the source of this.

**Comment by Jammy2211** [comment]
Pushed scripts on `master` of `autogalaxy_workspace` now fix this (using the `master` branch of PyAutoGalaxy).

I havent done the pip release yet, but will be sorted in the next week.
