### ISSUE TITLE
Update metadata in setup.py

### ISSUE THREAD

**Issue by pllim** [Jammy2211/PyAutoGalaxy#44]
I noticed some outdated metadata; for example:

https://github.com/Jammy2211/PyAutoGalaxy/blob/449d5a11c70439010a27d7ceffe20d4c6af13c48/setup.py#L38-L41

The older versions of Python here have all reached EOL and not tested in CI. Also see #45 

https://github.com/astropy/astropy.github.com/pull/491#issuecomment-1215349065

**Comment by Jammy2211** [comment]
Done https://github.com/Jammy2211/PyAutoGalaxy/blob/main/setup.py
