### ISSUE TITLE
MANIFEST.in is outdated

### ISSUE THREAD

**Issue by pllim** [Jammy2211/PyAutoGalaxy#46]
`MANIFEST.in` lists some files that no longer exist. Does it also accidentally not including new files? It needs to be audited to make sure that it is up-to-date and that it generates a good dist.

https://github.com/astropy/astropy.github.com/pull/491#issuecomment-1215349065

**Comment by Jammy2211** [comment]
Updated: https://github.com/Jammy2211/PyAutoGalaxy/blob/main/MANIFEST.in
