### ISSUE TITLE
Move to_do_list to issues or project board

### ISSUE THREAD

**Issue by pllim** [Jammy2211/PyAutoGalaxy#49]
To do list can be better tracked as proper GitHub issues. And maybe even list them on the GitHub Projects board for easier management.

https://github.com/astropy/astropy.github.com/pull/491#issuecomment-1215349065

**Comment by Jammy2211** [comment]
I have deleted the to_do_list.

In the near future, we will populate the issues with all planned functionality (we have a JOSS submission which will be accepted soon to go alongside this).

However, we are currently doing a lot of dev work so do not want to do this yet.
