### ISSUE TITLE
Binder example: Need to update stack, search.fit() broken

### ISSUE THREAD

**Issue by pllim** [Jammy2211/PyAutoGalaxy#55]
Nice [Binder example notebook](https://mybinder.org/v2/gh/Jammy2211/autogalaxy_workspace/release?filepath=introduction.ipynb) to allow someone to explore the package without installation. 👏 

However, when I ran it, I noticed a couple of things:

1. The software stack is quite old (Python 3.7, astropy 4.3.1). The current astropy LTS is in the 5.0.x series, so 4.x is no longer supported.
2. When I uncomment `result = search.fit(model=model, analysis=analysis)` cell in your notebook and ran it, I got a `AttributeError: 'ModelInstance' object has no attribute 'galaxies'`. If it is not meant to work, maybe remove it from the example? If it is supposed to work, then it needs to be fixed.
3. Some static images are not rendered but I am not sure if they are *expected* to or not in a Binder instance.

p.s. If you think this issue is better off moved to https://github.com/Jammy2211/autogalaxy_workspace/issues , feel free to do so. Thanks!

https://github.com/astropy/astropy.github.com/pull/491#issuecomment-1215349065

**Comment by Jammy2211** [comment]
Bug now fixed and binder runs on Python3.8.
