### ISSUE TITLE
Create a CITATION file

### ISSUE THREAD

**Issue by pllim** [Jammy2211/PyAutoGalaxy#60]
I see that you already set up multiple ways to cite this package (https://pyautogalaxy.readthedocs.io/en/latest/general/citations.html), which is very good! However, they are not exposed via CITATION file at the root directory.

Also see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

https://github.com/astropy/astropy.github.com/pull/491#issuecomment-1215349065

**Comment by pllim** [comment]
Hello. I see this is closed but it is not obvious to me which solution you have adopted. Hope you can clarify. Thanks!

**Comment by Jammy2211** [comment]
https://github.com/Jammy2211/PyAutoGalaxy/blob/main/CITATIONS.rst

**Comment by pllim** [comment]
Awesome. Thanks!
