### ISSUE TITLE
Clarify Papers page

### ISSUE THREAD

**Issue by pllim** [Jammy2211/PyAutoGalaxy#61]
At the time of posting this issue, there is nothing on https://pyautogalaxy.readthedocs.io/en/latest/general/papers.html , just a `¯_(ツ)_/¯`. Is there even any arXiv to link to? If not, the JOSS paper counts you mentioned in https://pyautogalaxy.readthedocs.io/en/latest/general/citations.html counts, right?

If there is indeed nothing to include on this page, consider removing it until you have materials.

https://github.com/astropy/astropy.github.com/pull/491#issuecomment-1215349065

**Comment by Jammy2211** [comment]
Removed page.
