### ISSUE TITLE
If Workspace is that important, why is it not in this repo?

### ISSUE THREAD

**Issue by pllim** [Jammy2211/PyAutoGalaxy#63]
From https://pyautogalaxy.readthedocs.io/en/latest/general/workspace.html and throughout the documentation, it seems like [autogalaxy workspace](https://github.com/Jammy2211/autogalaxy_workspace) is an integral part of this package (not merely optional supplementary material?). If so, why not include it as part of this package? (Can always exclude from the manifest if you do not want it in the sdist tarball.)

https://github.com/astropy/astropy.github.com/pull/491#issuecomment-1215349065

**Comment by pllim** [comment]
Related: If Workspace notebooks are indeed essential, consider adding Jupyter notebook installation instructions to the "conda" section of installation pages.

Or if you want to lock things down more, provide a conda environment YAML file.

**Comment by Jammy2211** [comment]
The primary reason is that the workspace contains notebooks and .fits datasets, which in the past have caused a lot of problems with bulking-out the repo history. By keeping them on a separate repo we avoid the source code history being noisy or (as was the case a long time ago) broken.

I also didn't find it much help having the workspace buried in the `site-packages` of an install.
