### ISSUE TITLE
TST: Add test coverage report

### ISSUE THREAD

**Issue by pllim** [Jammy2211/PyAutoGalaxy#66]
For example, using https://about.codecov.io/ and pytest coverage extension. Report that coverage as part of your CI and add a badge of that coverage in your README. If possible, shoot for 90% or better though I understand that is not always possible (e.g., if bulk of your code runs on numba and that isn't possible on Actions).

Also, I understand that high coverage does not mean all the edge cases are tested.

Bonus: Do consider using Hypothesis (https://hypothesis.readthedocs.io/) if you really care about catching edge cases where numerical computations are really important.

https://github.com/astropy/astropy.github.com/pull/491#issuecomment-1215349065

**Comment by Jammy2211** [comment]
Added https://github.com/Jammy2211/PyAutoGalaxy/pull/81
