### ISSUE TITLE
Astropy Integration: Configuration system

### ISSUE THREAD

**Issue by pllim** [Jammy2211/PyAutoGalaxy#69]
Looking at https://pyautogalaxy.readthedocs.io/en/latest/general/configs.html , looks like you utilize `autoconf`. Is there a reason why you opted not to use [astropy.config](https://docs.astropy.org/en/stable/config/index.html)?

https://github.com/astropy/astropy.github.com/pull/491#issuecomment-1215349065

**Comment by Jammy2211** [comment]
Many config files have complex structures which are not supports in astropy.config, for example the .json config files for priors on model components:

![image](https://user-images.githubusercontent.com/23455639/192098061-3a65f336-11c1-404c-9dcf-f9e01d48a241.png)

**Comment by pllim** [comment]
But what about the `.ini` ones?

**Comment by Jammy2211** [comment]
My concern would be this would then mean we are split using two separate `config` packages to manage config, which is a burden on development and creates two separate API's for the user. 

Also, unless I'm missing something, `astropy.config` seems to only support one config file at a time (which is the main `astropy` configuration file of the project in general?).

**Comment by pllim** [comment]
Yes, I guess it is more maintenance burden to keep two different config systems. Thanks for the clarification!

> only support one config file at a time

No, every package gets its own config file. However, for *each* package, only one config file will be active (though you can overwrite anything you want at run time but it won't "stick" unless you write it back out).
